# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 440e4351fd7bcc92241def5209b05aabbd355dfacbdf75e8a227ed7bfe595ac3d57fa75647a3fe639927f4ca4d11af8ec563bcb663fd336325d0994800eae47d

test:
  secret_key_base: db9c91fc3928daa34a8b6b2786ca0dcf64e0ed632fc1d637315b58f739d11828af5004d11121b933dfaa84bb9d942be96f0c1c3fe5f238eaf9506e66412d6e4a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
