# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
# coding: utf-8
Area.create(:area => '東嶺町')
Area.create(:area => '西嶺町')
Area.create(:area => '北嶺町')
Area.create(:area => '田園調布南')
Area.create(:area => '田園調布本町')
Area.create(:area => '田園調布')
Area.create(:area => '雪が谷大塚町')
Area.create(:area => '鵜の木')
Area.create(:area => '千鳥')
Area.create(:area => '南久が原')
Area.create(:area => '池上')
Area.create(:area => '久が原')
Area.create(:area => '南千束')
Area.create(:area => '北千束')
Area.create(:area => '石川町')
Area.create(:area => '仲池上')
Area.create(:area => '東雪谷')
Area.create(:area => '南雪谷')
Area.create(:area => '上池台')
Area.create(:area => '大森南')
Area.create(:area => '東糀谷')
Area.create(:area => '西糀谷')
Area.create(:area => '北糀谷')
Area.create(:area => '羽田旭町')
Area.create(:area => '羽田')
Area.create(:area => '本羽田')
Area.create(:area => '羽田空港')
Area.create(:area => '萩中')
Area.create(:area => '東六郷')
Area.create(:area => '西六郷')
Area.create(:area => '南六郷')
Area.create(:area => '仲六郷')
Area.create(:area => '千鳥')
Area.create(:area => '下丸子')
Area.create(:area => '矢口')
Area.create(:area => '多摩川')
Area.create(:area => '東蒲田')
Area.create(:area => '南蒲田')
Area.create(:area => '西蒲田')
Area.create(:area => '蒲田')
Area.create(:area => '蒲田本町')
Area.create(:area => '新蒲田')